version: '3.7'

services:
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.api.dev
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./server:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./server/.env.dev-sample
    depends_on:
      - db
      - redis
  db:
    build: 
      context: ./server
      dockerfile: Dockerfile.db.dev
    ports:
      - 5436:5432
    env_file:
      - ./server/.env.db.dev-sample
  redis:
    image: redis:6.0.5-alpine
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_SERVICE_URL=${REACT_APP_API_SERVICE_URL}
    depends_on:
      - api
    links:
      - api