"""empty message

Revision ID: 2031f622a14d
Revises: e5965c30d490
Create Date: 2020-12-15 09:20:04.553577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2031f622a14d'
down_revision = 'e5965c30d490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_token', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
