"""empty message

Revision ID: 2e81f9c8fc85
Revises: 84e43bb15a4f
Create Date: 2020-12-17 16:44:09.025217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e81f9c8fc85'
down_revision = '84e43bb15a4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('topics', sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'topics', ['updated_by'])
    op.create_unique_constraint(None, 'topics', ['created_by'])
    op.create_foreign_key(None, 'topics', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'topics', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'topics', ['id'], ['created_by'])
    op.create_foreign_key(None, 'users', 'topics', ['id'], ['updated_by'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_column('topics', 'updated_by')
    op.drop_column('topics', 'created_by')
    # ### end Alembic commands ###
