"""empty message

Revision ID: 3d91b08cec13
Revises: d1fd23a7fe87
Create Date: 2020-12-15 10:27:33.093218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d91b08cec13'
down_revision = 'd1fd23a7fe87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'active_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_token', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
