"""added messages table and its relations

Revision ID: 76aa99ee9d8d
Revises: 9c0f4acbcb2f
Create Date: 2020-12-16 12:31:18.483935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.api.utils import ISO8601DateTime


# revision identifiers, used by Alembic.
revision = '76aa99ee9d8d'
down_revision = '9c0f4acbcb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('topic_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', ISO8601DateTime(), nullable=False),
    sa.Column('updated_at', ISO8601DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
