"""empty message

Revision ID: 84e43bb15a4f
Revises: ac6c3029c1b6
Create Date: 2020-12-17 16:17:23.416577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e43bb15a4f'
down_revision = 'ac6c3029c1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'topics', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    # ### end Alembic commands ###
