"""empty message

Revision ID: 8e8b3d773dc6
Revises: eb08aa4281e2
Create Date: 2020-12-15 13:11:29.860767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8b3d773dc6'
down_revision = 'eb08aa4281e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'active_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
