"""Unique constraints for messages, topics, and users table.

Revision ID: a7be2f5753d1
Revises: b2606be714a7
Create Date: 2020-12-17 11:59:27.272530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7be2f5753d1'
down_revision = 'b2606be714a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'topics', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    # ### end Alembic commands ###
