"""empty message

Revision ID: ac6c3029c1b6
Revises: a7be2f5753d1
Create Date: 2020-12-17 16:15:25.172409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac6c3029c1b6'
down_revision = 'a7be2f5753d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'topics', ['id'])
    op.drop_constraint('topics_created_by_fkey', 'topics', type_='foreignkey')
    op.drop_constraint('topics_updated_by_fkey', 'topics', type_='foreignkey')
    op.drop_column('topics', 'updated_by')
    op.drop_column('topics', 'created_by')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('topics', sa.Column('created_by', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('topics', sa.Column('updated_by', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('topics_updated_by_fkey', 'topics', 'users', ['updated_by'], ['id'])
    op.create_foreign_key('topics_created_by_fkey', 'topics', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    # ### end Alembic commands ###
