"""added update constraint on updated_at columns

Revision ID: b034ed7cedcd
Revises: 76aa99ee9d8d
Create Date: 2020-12-17 06:09:34.606719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b034ed7cedcd'
down_revision = '76aa99ee9d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'messages', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='unique')
    # ### end Alembic commands ###
