"""empty message

Revision ID: c2336a40e355
Revises: 2e81f9c8fc85
Create Date: 2020-12-17 17:23:15.906983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2336a40e355'
down_revision = '2e81f9c8fc85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'messages', ['id'])
    op.drop_constraint('topics_created_by_key', 'topics', type_='unique')
    op.drop_constraint('topics_updated_by_key', 'topics', type_='unique')
    op.create_unique_constraint(None, 'topics', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'topics', type_='unique')
    op.create_unique_constraint('topics_updated_by_key', 'topics', ['updated_by'])
    op.create_unique_constraint('topics_created_by_key', 'topics', ['created_by'])
    op.drop_constraint(None, 'messages', type_='unique')
    # ### end Alembic commands ###
