"""empty message

Revision ID: d111607c9779
Revises: 88ec94fb4672
Create Date: 2020-12-27 07:05:40.667507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd111607c9779'
down_revision = '88ec94fb4672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'topics', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'topics', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    # ### end Alembic commands ###
