"""empty message

Revision ID: d1fd23a7fe87
Revises: 1b4fe88a45b5
Create Date: 2020-12-15 10:25:23.697621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fd23a7fe87'
down_revision = '1b4fe88a45b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_token', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'active_token_iat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_token_iat', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'active_token')
    # ### end Alembic commands ###
