"""empty message

Revision ID: e5965c30d490
Revises: 3e53babfb948
Create Date: 2020-12-15 09:05:13.638211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5965c30d490'
down_revision = '3e53babfb948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_token', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'active_token')
    # ### end Alembic commands ###
